'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, BarChart3, CalendarDays, CarFront, Check, ChevronDown, Heart, Menu, Moon, Search, ShieldCheck, SlidersHorizontal, Sparkles, Sun, X, Zap } from 'lucide-react'
import { calculateOwnership } from '../lib/ownership'
type Vehicle={name:string;year:number;price:number;fuel:string;km:string;tag?:string;color:string;ownership:ReturnType<typeof calculateOwnership>}
const vehicles:Vehicle[]=[
{name:'Toyota RAV4 GXL',year:2022,price:38990,fuel:'6.5L/100km',km:'42,100 km',tag:'Low ownership',color:'#c6d6da',ownership:calculateOwnership({price:38990,fuelCost:.11,serviceCost:780,years:5,annualKm:15000})},
{name:'Mazda CX-5 Touring',year:2021,price:34990,fuel:'7.4L/100km',km:'58,240 km',tag:'Best seller',color:'#ead9cb',ownership:calculateOwnership({price:34990,fuelCost:.12,serviceCost:850,years:5,annualKm:15000})},
{name:'Kia Sportage SX+',year:2023,price:42990,fuel:'6.3L/100km',km:'21,800 km',tag:'Just arrived',color:'#d6d9c7',ownership:calculateOwnership({price:42990,fuelCost:.11,serviceCost:720,years:5,annualKm:15000})},
{name:'Tesla Model 3 RWD',year:2022,price:46990,fuel:'Electric',km:'31,550 km',tag:'EV ready',color:'#cdd5e6',ownership:calculateOwnership({price:46990,fuelCost:.04,serviceCost:420,years:5,annualKm:15000})},
{name:'Hyundai i30 N-Line',year:2021,price:28990,fuel:'6.8L/100km',km:'47,900 km',color:'#ded7c3',ownership:calculateOwnership({price:28990,fuelCost:.11,serviceCost:750,years:5,annualKm:15000})},
{name:'Subaru Outback Sport',year:2020,price:31990,fuel:'7.3L/100km',km:'63,210 km',color:'#d0ddd5',ownership:calculateOwnership({price:31990,fuelCost:.12,serviceCost:900,years:5,annualKm:15000})},
{name:'Volkswagen Golf 110TSI',year:2022,price:30990,fuel:'6.2L/100km',km:'39,400 km',color:'#ddd1d0',ownership:calculateOwnership({price:30990,fuelCost:.11,serviceCost:880,years:5,annualKm:15000})},
{name:'Mitsubishi Outlander',year:2023,price:44990,fuel:'6.1L/100km',km:'19,780 km',color:'#d5d0dc',ownership:calculateOwnership({price:44990,fuelCost:.1,serviceCost:760,years:5,annualKm:15000})},
{name:'Ford Ranger XLT',year:2021,price:49990,fuel:'8.4L/100km',km:'54,600 km',color:'#d8ccb8',ownership:calculateOwnership({price:49990,fuelCost:.14,serviceCost:980,years:5,annualKm:15000})},
]
const types=['SUV','Hatch','Sedan','Ute','Electric','Hybrid']; const icons=['◒','▱','▭','▰','ϟ','◎']
function CarArt({vehicle,large=false}:{vehicle:Vehicle;large?:boolean}){return <div className={`car-art ${large?'large':''}`} style={{background:vehicle.color}}><div className="art-sun"/><div className="art-road"/><div className="art-car"><span/><i/><b/></div><small>TUTA / {vehicle.year}</small></div>}
function Label({children}:{children:string}){return <div className="section-label">{children}</div>}
export default function Home(){const[dark,setDark]=useState(true),[menu,setMenu]=useState(false),[query,setQuery]=useState(''),[type,setType]=useState(''),[budget,setBudget]=useState('Any budget'),[saved,setSaved]=useState<string[]>([]),[price,setPrice]=useState(38990),[deposit,setDeposit]=useState(5000),[term,setTerm]=useState(5),[booked,setBooked]=useState(false);const filtered=useMemo(()=>vehicles.filter(v=>v.name.toLowerCase().includes(query.toLowerCase())&&(type===''||(type==='Electric'?v.fuel==='Electric':type==='SUV'?['Toyota','Mazda','Kia','Subaru','Mitsubishi'].some(x=>v.name.startsWith(x)):true))&&(budget==='Any budget'||(budget==='Under $35k'?v.price<35000:v.price>=35000))),[query,type,budget]);const monthly=Math.round((price-deposit)/(term*12)*1.065);const show=vehicles[0].ownership;return <main className={dark?'site dark':'site light'}>
<header className="nav-shell"><a className="brand" href="#top"><span className="brand-mark">T</span>TUTA<span className="brand-muted">CARS</span></a><nav className={menu?'nav-links open':'nav-links'}><a href="#cars">Find a car</a><a href="#how">How it works</a><a href="#ownership">True cost</a><a href="#partners">For dealers</a></nav><div className="nav-actions"><button className="icon-button" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun size={17}/>:<Moon size={17}/>}</button><a className="text-button" href="#signin">Sign in</a><a className="nav-cta" href="#cars">Browse cars <ArrowRight size={15}/></a><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X size={20}/>:<Menu size={20}/>}</button></div></header>
<section className="hero" id="top"><div className="hero-copy"><div className="eyebrow"><span/> Car buying, made clear.</div><h1>The right car.<br/><em>Without the runaround.</em></h1><p>Independent inspections. Real ownership costs. A better way to find your next car.</p><div className="hero-proof"><span><Check size={14}/> 2,400+ cars inspected</span><span><Check size={14}/> 48-hour test drives</span><span><Check size={14}/> No dealer pressure</span></div></div><div className="search-card"><div className="search-head"><div><span>START YOUR SEARCH</span><h2>What are you looking for?</h2></div><Sparkles size={21}/></div><div className="search-input"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Make, model or keyword"/><kbd>⌘ K</kbd></div><div className="filter-row"><label>Body type<select value={type} onChange={e=>setType(e.target.value)}><option value="">Any type</option>{types.map(t=><option key={t}>{t}</option>)}</select></label><label>Budget<select value={budget} onChange={e=>setBudget(e.target.value)}><option>Any budget</option><option>Under $35k</option><option>$35k and over</option></select></label><button className="search-submit" onClick={()=>document.getElementById('cars')?.scrollIntoView({behavior:'smooth'})}>Search cars <ArrowRight size={16}/></button></div><div className="search-note"><ShieldCheck size={14}/> Every car comes with an independent condition report.</div></div></section>
<section className="body-section"><Label>BROWSE BY TYPE</Label><div className="body-grid">{types.map((t,i)=><button className={type===t?'body-card active':'body-card'} key={t} onClick={()=>setType(type===t?'':t)}><b>{icons[i]}</b><span>{t}</span><ArrowRight size={14}/></button>)}</div></section>
<section className="ownership-section" id="ownership"><div className="ownership-intro"><Label>THE TUTA DIFFERENCE</Label><h2>Price is only<br/><em>the beginning.</em></h2><p>We show you what a car really costs to own, so you can compare with confidence—not just a tempting sticker price.</p><a className="under-link" href="#how">How we calculate it <ArrowRight size={15}/></a></div><div className="cost-card"><div className="cost-top"><span><BarChart3 size={14}/> TRUE COST OF OWNERSHIP</span><small>Over 5 years</small></div><div className="cost-car"><CarArt vehicle={vehicles[0]} large/><div><span>A SMARTER CHOICE</span><h3>Toyota RAV4 GXL</h3><p>2022 · 42,100 km · Petrol</p></div></div><div className="cost-stats"><div><span>Effective monthly</span><strong>${Math.round(show.monthlyCost).toLocaleString()}</strong></div><div><span>Cost per kilometre</span><strong>${show.costPerKm.toFixed(2)}</strong></div><div><span>Value score</span><strong className="score">{show.valueScore}<small>/10</small></strong></div></div><div className="cost-footer"><span><Check size={16}/> {show.badge} for long-term value</span><a href="#cars">See the maths <ArrowRight size={14}/></a></div></div></section>
<section className="how-section" id="how"><div className="section-heading"><div><Label>A BETTER WAY TO BUY</Label><h2>From search to keys.<br/><em>On your terms.</em></h2></div><p>No awkward sales calls. No mystery fees. Just a simple, transparent process designed around you.</p></div><div className="steps">{[['01',Search,'Find your shortlist','Compare cars by the numbers that actually matter to you.'],['02',ShieldCheck,'Know what you’re buying','Every vehicle is independently inspected and honestly described.'],['03',CalendarDays,'Take it for a proper drive','Book a 48-hour test drive from home. No pressure, ever.'],['04',CarFront,'Make it yours','We handle the paperwork and deliver to your door.']].map(([n,I,title,text])=><div className="step" key={n as string}><span>{n as string}</span><div className="step-icon"><I size={22}/></div><h3>{title as string}</h3><p>{text as string}</p></div>)}</div></section>
<section className="cars-section" id="cars"><div className="section-heading cars-heading"><div><Label>READY WHEN YOU ARE</Label><h2>Cars worth<br/><em>looking twice at.</em></h2></div><div className="cars-controls"><button className="filter-button"><SlidersHorizontal size={15}/> Filters</button><button className="sort-button">Most relevant <ChevronDown size={15}/></button></div></div><div className="cars-grid">{filtered.map(v=><article className="car-card" key={v.name}><div className="card-image"><CarArt vehicle={v}/><button className={saved.includes(v.name)?'heart saved':'heart'} onClick={()=>setSaved(saved.includes(v.name)?saved.filter(x=>x!==v.name):[...saved,v.name])} aria-label={`Save ${v.name}`}><Heart size={17} fill={saved.includes(v.name)?'currentColor':'none'}/></button>{v.tag&&<span className="listing-tag">{v.tag}</span>}</div><div className="card-content"><div className="card-title"><div><h3>{v.name}</h3><p>{v.year} · {v.km}</p></div><b>${v.price.toLocaleString()}</b></div><div className="card-meta"><span><Zap size={13}/> {v.fuel}</span><span><BarChart3 size={13}/> ${v.ownership.costPerKm.toFixed(2)}/km</span></div><div className="card-bottom"><span>Est. ${Math.round(v.ownership.monthlyCost)}/mo</span><a href="#drive">View car <ArrowRight size={14}/></a></div></div></article>)}</div><button className="outline-cta">View all 84 cars <ArrowRight size={16}/></button></section>
<section className="drive-banner" id="drive"><div className="drive-art"><div>48<small>HOURS</small></div></div><div className="drive-copy"><Label>NO RUSH, NO PRESSURE</Label><h2>Take your time.<br/><em>Literally.</em></h2><p>Every Tuta car is available for a 48-hour test drive, delivered to your door. Live with it. Load it up. See if it fits your life.</p><button className="light-cta" onClick={()=>setBooked(true)}>{booked?<><Check size={16}/> Request received</>:<>Book a test drive <ArrowRight size={16}/></>}</button></div></section>
<section className="trust-section" id="partners"><div className="trust-copy"><Label>BUILT ON TRUST</Label><h2>Every car has a<br/><em>story. We show it.</em></h2><p>Our inspection partners check the details dealers leave out—so you know the good, the bad, and everything in between.</p><div className="trust-list"><span><Check size={15}/> 150-point inspection</span><span><Check size={15}/> Independent inspectors</span><span><Check size={15}/> 7-day money-back promise</span></div></div><div className="inspection-pods"><div className="pod pod-large"><span>01</span><h3>Condition<br/>report</h3><p>Clear, honest and easy to understand.</p><ShieldCheck size={37}/></div><div className="pod"><span>02</span><h3>History<br/>checked</h3><p>We look under every hood.</p></div><div className="pod"><span>03</span><h3>Dealer<br/>vetted</h3><p>Good people, good cars.</p></div></div></section>
<section className="finance-section" id="finance"><div><Label>MAKE IT WORK FOR YOU</Label><h2>Finance that<br/><em>makes sense.</em></h2><p>See your repayments upfront, without a hard credit check or a surprise at the end.</p></div><div className="finance-card"><span>YOUR ESTIMATED REPAYMENT</span><strong>${monthly.toLocaleString()}<small>/ month</small></strong><label>Car price <output>${price.toLocaleString()}</output><input type="range" min="20000" max="70000" step="1000" value={price} onChange={e=>setPrice(+e.target.value)}/></label><label>Deposit <output>${deposit.toLocaleString()}</output><input type="range" min="0" max="20000" step="500" value={deposit} onChange={e=>setDeposit(+e.target.value)}/></label><div className="finance-options">{[3,5,7].map(n=><button key={n} className={term===n?'active':''} onClick={()=>setTerm(n)}>{n} years</button>)}</div><small>Indicative only. Subject to lender approval.</small></div></section>
<footer><div className="footer-top"><div><a className="brand" href="#top"><span className="brand-mark">T</span>TUTA<span className="brand-muted">CARS</span></a><p>Better car buying starts here.</p></div><div className="footer-links"><div><b>Explore</b><a href="#cars">Find a car</a><a href="#ownership">True cost</a><a href="#how">How it works</a></div><div><b>Company</b><a href="#partners">Our story</a><a href="#partners">For dealers</a><a href="#partners">Contact</a></div><div><b>Help</b><a href="#drive">Test drives</a><a href="#finance">Finance</a><a href="#top">FAQs</a></div></div></div><div className="footer-bottom"><span>© 2026 Tuta Cars. Clearer by design.</span><span>Privacy · Terms · NZ</span></div></footer></main>}
